version: 2.1
orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: "circleci/node:12.18.1"
    steps:
      - checkout
      - node/install:
          npm-version: latest
          node-version: 12.18.1
      - run:
          command: npm ci
      - slack/status:
          failure_message: ":red_circle: $CIRCLE_JOB job has failed!"
          success_message: ":tada: $CIRCLE_JOB job has succeeded!"

  test:
    docker:
      - image: "circleci/node:12.18.1"
    steps:
      - checkout
      - node/install:
          npm-version: latest
          node-version: 12.18.1
      - run:
          command: npm ci
      - run:
          command: npm run test:unit
      - run:
          command: npm run test:unit:cov
      - run:
          command: npm run report-coverage -- -t $CODECOV_TOKEN
      - slack/status:
          failure_message: ":red_circle: $CIRCLE_JOB job has failed!"
          success_message: ":tada: $CIRCLE_JOB job has succeeded!"  

  publish:
    docker:
      - image: "circleci/node:12.18.1"
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Publish to Github packages
          command: |
            echo "$DOCKER_PASS" | docker login docker.pkg.github.com -u $DOCKER_USER --password-stdin
            docker build -t docker.pkg.github.com/geodoo/post-your-standup/post-your-standup:latest -f Dockerfile.prod .
            docker push docker.pkg.github.com/geodoo/post-your-standup/post-your-standup:latest
      - slack/status:
          failure_message: ":red_circle: $CIRCLE_JOB job has failed!"
          success_message: ":tada: $CIRCLE_JOB job has succeeded!"

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0f:22:e5:20:ef:19:e2:1a:a6:bf:5d:0c:87:84:40:44"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST 'cd /var/www/html/post-your-standup/ &&
            git checkout master &&
            git pull &&
            npm install && 
            npm run prod:restart'
      - slack/status:
          failure_message: ":red_circle: $CIRCLE_JOB job has failed!"
          success_message: ":tada: $CIRCLE_JOB job has succeeded!"

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
