name: Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: GeoDoo/post-your-standup/post-your-standup
          registry: docker.pkg.github.com
          username: ${{ secrets.GB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: prod.Dockerfile
          tags: latest
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          GB_USERNAME: ${{ secrets.GB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: GB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q)
            docker login docker.pkg.github.com -u $GB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/GeoDoo/post-your-standup/post-your-standup:latest
            docker run -dit -p 80:3000 docker.pkg.github.com/GeoDoo/post-your-standup/post-your-standup:latest
